language_map = {
    'as': 'Assamese',
    'bn': 'Bengali',
    'gu': 'Gujarati',
    'hi': 'Hindi',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'mni': 'Manipuri',
    'mr': 'Marathi',
    'or': 'Oriya',
    'pa': 'Punjabi',
    'ta': 'Tamil',
    'te': 'Telugu',
    'ur': 'Urdu',
    'sa': 'Sanskrit',
    'en': 'English',
    'sd': 'Sindhi',
    'brx': 'Bodo',
    'doi': 'Dogri',
    'ks': 'Kashmiri',
    'sat': 'Santali',
    'mai': 'Maithili',
    'kok': 'Konkani',
    'ne': 'Nepali'
}